### ISSUE TITLE
Floating point issue during validation in sde.init

### ISSUE THREAD

**Issue by sourav-majumdar-math** [mlysy/msde#8]
I encountered `Invalid sde complete data.` error when working with somewhat large data and considering large `m` greater than 1 in `sde.init`. I was able to identify the issue to the following code. What happens is that the last row in the `init.data` variable is returned `NA`. This is due to the last element of `told` and `tnew` being different, the difference is of the order of `e-15`. This causes the last interpolating value to become `NA` since the last element of `tnew` doesn't exist in `told`.

I have isolated the relevant code from `sde.init` to create a reproducible example for the bug.

```
set.seed(100)

m<-6
dt<-1/365
X_obs<-matrix(rnorm(8000),nrow=4000,ncol=2)

ncomp<-((nrow(X_obs)-1)*m+1)
ndims<-ncol(X_obs)

x <- .format.data(X_obs, c("x1", "x2"), type = "matrix", strict = TRUE)
x <- t(x)
init.data <- matrix(NA, ncomp, ndims)
dt <- rep(dt, nrow(x)-1)
dtnew <- rep((dt)/m, each = m)
told <- cumsum(c(0, dt))
tnew <- cumsum(c(0, dtnew))
for(ii in 1:2) {
  init.data[,ii] <- approx(x = told, y = x[,ii],
                           xout = tnew)$y
}
```
`init.data[ncomp, ]` returns `NA NA`

**Comment by mlysy** [comment]
Thanks.  This is now fixed in the github version of the package.
